suffixes_to_remove = [
    " AARE", 
    " AP",
    ", AIA",
    ", ALC",
    " CCIM",
    ", CCIM",
    ",CCIM",
    ", CIPS",
    ", CLS",
    ", CPA",
    " CPM",
    ", CPM",
    ",CPM",
    ", CRE",
    ", CRRP",
    ", CRS",
    ", CSM",
    ", D.B.A",
    ", EdD",
    ",  Esq.",
    ", ESQ",
    ", Esq.",
    ", GC",
    ", GRI",
    ", II",
    "III",
    "IV",
    ", IV",
    ", J.D.",
    ", JD",
    " JD",
    " (Jim)",
    " Jr.",
    ",Jr.",
    ", JR",
    ", LEED",
    ", LLC",
    ",MBA",
    ", M.B.A",
    " MAI",
    ", MAI",
    ", MBA",
    ", MCR",
    ", MiCP",
    ", MSIRE",
    ", MSRE",
    ", P.A",
    ", P.A.",
    ", PA",
    ", PhD",
    ", PLS",
    ", Realtor",
    ", RPA",
    ", SEC",
    ",SIOR",
    "/SIOR",
    " SIOR",
    ", SIOR",
    ", Sr",
    ", Sr.",
    ", SRA",
  ]

special_characters_to_replace = {
    "é" : "&eacute;",
    "à" : "&agrave;",
    "è" : "&egrave;",
    "ù" : "&ugrave;",
    "â" : "&acirc;",
    "ê" : "&ecirc;",
    "î" : "&icirc;",
    "ô" : "&ocirc;",
    "û" : "&ucirc;",
    "ë" : "&euml;",
    "ï" : "&iuml;",
    "ü" : "&uuml;",
    "ç" : "&ccedil;",
    "ö" : "&ouml;",
    "õ" : "&otilde;",
    "ó" : "&oacute;",
    "ò" : "&ograve;",
    "á" : "&aacute;",
    "æ" : "&aelig;",
    "ñ" : "&ntilde;",
    "'" : "&apos;",
    "‘" : "&lsquo;",
    "’" : "&rsquo;",
    "“" : "&ldquo;",
    "”" : "&rdquo;",
    "£" : "&pound;",
  }   

punctuation_to_remove = [";", ",", "|"]

we_proccess_status = [
  'Contact Opted Out',
  'Email Verification Not Valid (email_account_invalid)',
  'Email Verification Not Valid (email_domain_invalid)',
  'Processed',
  'Contact Missing Required Info',
  'Contact Not In WE'
]